drop table Player_score;
drop table Match_Up;
drop table Team_Player;
drop table User_team;
drop table Fantasy_League;
drop table User_Profile;
drop table Player;
drop table Pro_team;
drop table Pro_League;